const SubmissionStatuses = {
  DRAFT: 'DRAFT',
  PAYMENT_PENDING: 'PAYMENT_PENDING',
  SUBMITTED: 'SUBMITTED',
  UNDER_REVIEW: 'UNDER_REVIEW',
  DECISION_MADE: 'DECISION_MADE',
  WITHDRAWN: 'WITHDRAWN',
};

const SubmissionTimelineTypes = {
  CREATED: 'CREATED',
  FILE_UPLOADED: 'FILE_UPLOADED',
  PAYMENT_INTENT_CREATED: 'PAYMENT_INTENT_CREATED',
  PAYMENT_CONFIRMED: 'PAYMENT_CONFIRMED',
  SUBMITTED: 'SUBMITTED',
  WITHDRAWN: 'WITHDRAWN',
  STATUS_CHANGED: 'STATUS_CHANGED',
  DECISION_SET: 'DECISION_SET',
};

module.exports = {
  SubmissionStatuses,
  SubmissionTimelineTypes,
};
